//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdNameService { get; set; }
    
        public virtual AvailableServicesSet AvailableServicesSet { get; set; }
        public virtual ClientsSet ClientsSet { get; set; }
    }
}
